const SIGNIN_METHOD_MAP = {
  GOOGLE: "GOOGLE",
  APPLE: "APPLE",
};

const SIGNIN_METHODS = [SIGNIN_METHOD_MAP.GOOGLE, SIGNIN_METHOD_MAP.APPLE];

module.exports = {
  SIGNIN_METHOD_MAP,
  SIGNIN_METHODS,
};
